# https://taskfile.dev

version: '3'

vars:
  BUILD_DIR: "{{ .ROOT_DIR }}/bin"

env:
  LOG_LEVEL: "debug"

tasks:
  test-cover:
    cmds:
      - go clean -cache -testcache
      - go test
            -covermode=atomic
            -coverpkg=./...
            -coverprofile=coverage.out
            ./...
      - go tool cover -func=coverage.out
      - go-cover-treemap -coverprofile coverage.out -percent > "{{ .ROOT_DIR }}/contrib/coverage.svg"

  test:
    cmds:
      - task: generate
      - go test -v ./...

  generate:
    cmds:
      - go generate -v ./...

  generate-reset:
    cmds:
      - go generate -v ./cmd/reset/

  lint:
    cmds:
      - golangci-lint-v2 run

  test-lint:
    cmds:
      - task: test
      - task: lint

  lint-custom:
    cmd: go run cmd/linter/main.go cmd/linter/customanalyzer.go ./...

  create-keys:
    cmd: go run cmd/keygen/main.go --out-dir {{ .ROOT_DIR }}/contrib/keys

  compile-proto:
    cmd: |
      protoc \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go_opt=default_api_level=API_OPAQUE \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        internal/proto/metrics.proto

  build-dev:
    vars:
      BUILD_VERSION: "0.0.0"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%d %H:%M:%S"
      BUILD_COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
    cmds:
      - task: generate
      - mkdir -p {{ .BUILD_DIR }}
      - >
        go build -tags dev
        -ldflags "-X 'main.buildVersion={{ .BUILD_VERSION }}-{{ .BUILD_COMMIT }}'
        -X 'main.buildDate={{ .BUILD_DATE }}'
        -X 'main.buildCommit={{ .BUILD_COMMIT }}'"
        -o {{ .BUILD_DIR }}
        {{ .ROOT_DIR }}/cmd/...

  run-server:
    cmds:
      - task: generate
      - go run -tags=dev {{ .ROOT_DIR }}/cmd/server/*.go {{ .CLI_ARGS }}

  run-server-pg:
    vars:
      DATABASE_URI: "postgresql://localhost:5432/yandexdevmetrics?sslmode=disable"
    cmds:
      - task: build-dev
      - defer: psql -d postgres -c "DROP DATABASE IF EXISTS yandexdevmetrics"
      - psql -d postgres -c "DROP DATABASE IF EXISTS yandexdevmetrics"
      - psql -d postgres -c "CREATE DATABASE yandexdevmetrics"
      - >
        go run \
          {{ .ROOT_DIR }}/cmd/server/*.go \
          -d "{{ .DATABASE_URI }}"

  run-agent:
    cmds:
      - task: generate
      - go run -tags=dev {{ .ROOT_DIR }}/cmd/agent/*.go {{ .CLI_ARGS }}

  run-metricstest:
    cmds:
      - task: "run-metricstest:"

  run-metricstest:*:
    vars:
      TEST_SET_NUM: "{{ index .MATCH 0 | default 9 }}"
      SERVER_PORT: 41112
      ADDRESS: "localhost:${SERVER_PORT}"
      TEMP_FILE: /tmp/test.json
    cmds:
      - task: build-dev
      - metricstest -test.v -test.run=^TestIteration{{ .TEST_SET_NUM }}$
          -agent-binary-path={{ .BUILD_DIR }}/agent
          -binary-path={{ .BUILD_DIR }}/server
          -file-storage-path={{ .TEMP_FILE }}
          -server-port={{ .SERVER_PORT }}
          -source-path=.
      - rm -f {{ .TEMP_FILE }}

  run-metricstest-pg:*:
    vars:
      TEST_SET_NUM: "{{ index .MATCH 0 | default 9 }}"
      SERVER_PORT: 41112
      ADDRESS: "localhost:${SERVER_PORT}"
      DATABASE_DSN: postgresql://yx:yx@localhost:5432/yandex-metrics?sslmode=disable
    cmds:
      - task: build-dev
      - metricstest -test.v -test.run=^TestIteration{{ .TEST_SET_NUM }}$
          -agent-binary-path={{ .BUILD_DIR }}/agent
          -binary-path={{ .BUILD_DIR }}/server
          -database-dsn={{ .DATABASE_DSN }}
          -server-port={{ .SERVER_PORT }}
          -source-path=.
      - rm -f {{ .TEMP_FILE }}
