// Code generated by cmd/reset DO NOT EDIT
package config

import "reflect"

func (c *AgentConfig) Reset() {
    if c == nil {
        return
    }

    v := reflect.ValueOf(c).Elem()
    resetValue(v)
}

func (c *ServerConfig) Reset() {
    if c == nil {
        return
    }

    v := reflect.ValueOf(c).Elem()
    resetValue(v)
}

func resetValue(v reflect.Value) {
    if !v.IsValid() || !v.CanSet() {
        return
    }

    switch v.Kind() {
    case reflect.Ptr:
        if !v.IsNil() {
            resetValue(v.Elem())
        }
    case reflect.Struct:
        if resetter, ok := v.Addr().Interface().(interface{ Reset() }); ok {
            resetter.Reset()
            return
        }
        for i := 0; i < v.NumField(); i++ {
            field := v.Field(i)
            if field.CanSet() {
                resetValue(field)
            }
        }
    case reflect.Slice:
        if v.Len() > 0 {
            v.SetLen(0)
        }
    case reflect.Map:
        if v.Len() > 0 {
            v.Clear()
        }
    case reflect.String:
        v.SetString("")
    case reflect.Bool:
        v.SetBool(false)
    case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
        v.SetInt(0)
    case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
        v.SetUint(0)
    case reflect.Float32, reflect.Float64:
        v.SetFloat(0)
    case reflect.Complex64, reflect.Complex128:
        v.SetComplex(0)
    }
}
